# Generated by Django 6.0.5 on 2026-05-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('genre', models.CharField(max_length=100, verbose_name='Género')),
                ('director_name', models.CharField(max_length=150, verbose_name='Director')),
                ('publication_year', models.IntegerField(verbose_name='Año de publicación')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-publication_year', 'title'],
            },
        ),
    ]
